{
  "openapi": "3.0.1",
  "info": {
    "title": "Lucidtech API",
    "version": "2021-02-16T15:30:45Z"
  },
  "servers": [
    {
      "url": "https://api.lucidtech.ai/{basePath}",
      "variables": {
        "basePath": {
          "default": "v1"
        }
      }
    }
  ],
  "paths": {
    "/assets": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/assets.get"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/assets.post"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/assets/{assetId}": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/assets.assetid.get"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/assets.assetid.patch"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/batches": {
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/batches.post"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/documents": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents.delete"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents.get"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents.post"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/documents/{documentId}": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents.documentid.get"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents.documentid.patch"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/logs": {
      "options": {
      }
    },
    "/logs/{logId}": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/logs.logid.get"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      }
    },
    "/models": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/models.get"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      }
    },
    "/predictions": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/predictions.get"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/predictions.post"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/secrets": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/secrets.get"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/secrets.post"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/secrets/{secretId}": {
      "options": {
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/secrets.secretid.patch"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/transitions": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions.get"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions.post"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/transitions/{transitionId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions.transitionid.delete"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions.transitionid.get"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions.transitionid.patch"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/transitions/{transitionId}/executions": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions.transitionid.executions.get"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions.transitionid.executions.post"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/transitions/{transitionId}/executions/{executionId}": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions.transitionid.executions.executionid.get"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions.transitionid.executions.executionid.patch"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/users": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/users.get"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/users.post"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/users/{userId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/users.userid.delete"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/users.userid.get"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/users.userid.patch"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/workflows": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows.get"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows.post"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/workflows/{workflowId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows.workflowid.delete"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows.workflowid.get"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows.workflowid.patch"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/workflows/{workflowId}/executions": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows.workflowid.executions.get"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows.workflowid.executions.post"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/workflows/{workflowId}/executions/{executionId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows.workflowid.executions.executionid.delete"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      }
    }
  },
  "components": {
    "securitySchemes": {
      "api_key": {
        "type": "apiKey",
        "name": "x-api-key",
        "in": "header"
      },
      "OAuth2": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://auth.lucidtech.ai/oauth2/token",
            "scopes": {
              "api.lucidtech.ai/assets.get": "Scope for GET /assets",
              "api.lucidtech.ai/documents.documentid.patch": "Scope for PATCH /documents/{documentId}",
              "api.lucidtech.ai/assets.assetid.patch": "Scope for PATCH /assets/{assetId}",
              "api.lucidtech.ai/transitions.transitionid.executions.executionid.patch": "Scope for PATCH /transitions/{transitionId}/executions/{executionId}",
              "api.lucidtech.ai/users.get": "Scope for GET /users",
              "api.lucidtech.ai/transitions.transitionid.patch": "Scope for PATCH /transitions/{transitionId}",
              "api.lucidtech.ai/assets.assetid.get": "Scope for GET /assets/{assetId}",
              "api.lucidtech.ai/users.userid.patch": "Scope for PATCH /users/{userId}",
              "api.lucidtech.ai/secrets.get": "Scope for GET /secrets",
              "api.lucidtech.ai/workflows.workflowid.delete": "Scope for DELETE /workflows/{workflowId}",
              "api.lucidtech.ai/documents.documentid.get": "Scope for GET /documents/{documentId}",
              "api.lucidtech.ai/transitions.transitionid.executions.get": "Scope for GET /transitions/{transitionId}/executions",
              "api.lucidtech.ai/batches.post": "Scope for POST /batches",
              "api.lucidtech.ai/transitions.transitionid.executions.post": "Scope for POST /transitions/{transitionId}/executions",
              "api.lucidtech.ai/documents.get": "Scope for GET /documents",
              "api.lucidtech.ai/users.userid.get": "Scope for GET /users/{userId}",
              "api.lucidtech.ai/models.get": "Scope for GET /models",
              "api.lucidtech.ai/secrets.post": "Scope for POST /secrets",
              "api.lucidtech.ai/users.post": "Scope for POST /users",
              "api.lucidtech.ai/workflows.post": "Scope for POST /workflows",
              "api.lucidtech.ai/secrets.secretid.patch": "Scope for PATCH /secrets/{secretId}",
              "api.lucidtech.ai/documents.post": "Scope for POST /documents",
              "api.lucidtech.ai/workflows.workflowid.patch": "Scope for PATCH /workflows/{workflowId}",
              "api.lucidtech.ai/assets.post": "Scope for POST /assets",
              "api.lucidtech.ai/predictions.post": "Scope for POST /predictions",
              "api.lucidtech.ai/transitions.transitionid.get": "Scope for GET /transitions/{transitionId}",
              "api.lucidtech.ai/transitions.post": "Scope for POST /transitions",
              "api.lucidtech.ai/transitions.get": "Scope for GET /transitions",
              "api.lucidtech.ai/predictions.get": "Scope for GET /predictions",
              "api.lucidtech.ai/workflows.workflowid.executions.get": "Scope for GET /workflows/{workflowId}/executions",
              "api.lucidtech.ai/transitions.transitionid.delete": "Scope for DELETE /transitions/{transitionId}",
              "api.lucidtech.ai/workflows.get": "Scope for GET /workflows",
              "api.lucidtech.ai/logs.logid.get": "Scope for GET /logs/{logId}",
              "api.lucidtech.ai/users.userid.delete": "Scope for DELETE /users/{userId}",
              "api.lucidtech.ai/workflows.workflowid.executions.post": "Scope for POST /workflows/{workflowId}/executions",
              "api.lucidtech.ai/workflows.workflowid.get": "Scope for GET /workflows/{workflowId}",
              "api.lucidtech.ai/transitions.transitionid.executions.executionid.get": "Scope for GET /transitions/{transitionId}/executions/{executionId}",
              "api.lucidtech.ai/workflows.workflowid.executions.executionid.delete": "Scope for DELETE /workflows/{workflowId}/executions/{executionId}",
              "api.lucidtech.ai/documents.delete": "Scope for DELETE /documents"
            }
          }
        }
      }
    }
  }
}