{
  "openapi": "3.0.1",
  "info": {
    "title": "Lucidtech API",
    "version": "2021-05-19T09:10:50Z"
  },
  "servers": [
    {
      "url": "https://api.lucidtech.ai/{basePath}",
      "variables": {
        "basePath": {
          "default": "v1"
        }
      }
    }
  ],
  "paths": {
    "/appClients": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/appclients:read"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/appclients:write"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/appClients/{appClientId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/appclients:write"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/appclients:write"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/assets": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/assets:read"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/assets:write"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/assets/{assetId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/assets:write"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/assets:read"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/assets:write"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/batches": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/batches:read"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/batches:write"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/batches/{batchId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/batches:write"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/batches:write"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/documents": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:write"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:read"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:write"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/documents/{documentId}": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:read"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:write"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/logs": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/logs:read"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      }
    },
    "/logs/{logId}": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/logs:read"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      }
    },
    "/models": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/models:read"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/models:write"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/models/{modelId}": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/models:read"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/models:write"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/predictions": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/predictions:read"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/predictions:write"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/secrets": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/secrets:read"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/secrets:write"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/secrets/{secretId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/secrets:write"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/secrets:write"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/transitions": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions:read"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions:write"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/transitions/{transitionId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions:write"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions:read"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions:write"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/transitions/{transitionId}/executions": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions.executions:read"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions.executions:write"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/transitions/{transitionId}/executions/{executionId}": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions.executions:read"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions.executions:write"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/transitions/{transitionId}/executions/{executionId}/heartbeats": {
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions.executions.heartbeats:write"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/users": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/users:read"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/users:write"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/users/{userId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/users:write"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/users:read"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/users:write"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/workflows": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows:read"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows:write"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/workflows/{workflowId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows:write"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows:read"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows:write"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/workflows/{workflowId}/executions": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows.executions:read"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows.executions:write"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/workflows/{workflowId}/executions/{executionId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows.executions:write"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows.executions:read"
            ]
          },
          {
            "api_key": []
          }
        ]
      },
      "options": {
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows.executions:write"
            ]
          },
          {
            "api_key": []
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "api_key": {
        "type": "apiKey",
        "name": "x-api-key",
        "in": "header"
      },
      "OAuth2": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://auth.lucidtech.ai/oauth2/token",
            "scopes": {
              "api.lucidtech.ai/batches:write": "Scope for DELETE /batches/{batchId}",
              "api.lucidtech.ai/logs:read": "Scope for GET /logs/{logId}",
              "api.lucidtech.ai/users:read": "Scope for GET /users/{userId}",
              "api.lucidtech.ai/transitions:write": "Scope for DELETE /transitions/{transitionId}",
              "api.lucidtech.ai/assets:write": "Scope for DELETE /assets/{assetId}",
              "api.lucidtech.ai/transitions.executions.heartbeats:write": "Scope for POST /transitions/{transitionId}/executions/{executionId}/heartbeats",
              "api.lucidtech.ai/secrets:read": "Scope for GET /secrets",
              "api.lucidtech.ai/transitions:read": "Scope for GET /transitions/{transitionId}",
              "api.lucidtech.ai/predictions:read": "Scope for GET /predictions",
              "api.lucidtech.ai/users:write": "Scope for PATCH /users/{userId}",
              "api.lucidtech.ai/assets:read": "Scope for GET /assets/{assetId}",
              "api.lucidtech.ai/workflows.executions:write": "Scope for PATCH /workflows/{workflowId}/executions/{executionId}",
              "api.lucidtech.ai/transitions.executions:write": "Scope for PATCH /transitions/{transitionId}/executions/{executionId}",
              "api.lucidtech.ai/appclients:write": "Scope for DELETE /appClients/{appClientId}",
              "api.lucidtech.ai/workflows:write": "Scope for PATCH /workflows/{workflowId}",
              "api.lucidtech.ai/models:read": "Scope for GET /models/{modelId}",
              "api.lucidtech.ai/predictions:write": "Scope for POST /predictions",
              "api.lucidtech.ai/appclients:read": "Scope for GET /appClients",
              "api.lucidtech.ai/models:write": "Scope for PATCH /models/{modelId}",
              "api.lucidtech.ai/secrets:write": "Scope for DELETE /secrets/{secretId}",
              "api.lucidtech.ai/documents:read": "Scope for GET /documents/{documentId}",
              "api.lucidtech.ai/documents:write": "Scope for PATCH /documents/{documentId}",
              "api.lucidtech.ai/batches:read": "Scope for GET /batches",
              "api.lucidtech.ai/workflows:read": "Scope for GET /workflows/{workflowId}",
              "api.lucidtech.ai/transitions.executions:read": "Scope for GET /transitions/{transitionId}/executions/{executionId}",
              "api.lucidtech.ai/workflows.executions:read": "Scope for GET /workflows/{workflowId}/executions/{executionId}"
            }
          }
        }
      }
    }
  }
}