# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

---
name: Update SDK references

on:
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check out my python sdk
        uses: actions/checkout@master
        with:
          repository: LucidtechAI/las-sdk-python
          path: python-sdk

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: python sdk
        run: |
          ls
          cd python-sdk
          pip install requirements.docs.txt
          make docs
          mv docs/las.md reference/python-sdk/latest.md
          git add reference/python-sdk/latest.md
          git commit -m 'Automatically update python SDK reference'
          git push -u origin auto/update-python-sdk-reference
          git status
          EOF

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update SDK reference docs
          title: Update SDK reference docs
          body: This is an auto-generated PR with updated docs from the SDK.
          labels: automated pr
          branch: auto/update-sdk-reference
