# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

---
name: Update SDK references

on:
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check out my python sdk
        uses: actions/checkout@master
        with:
          repository: LucidtechAI/las-sdk-python
          path: python-sdk

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Python SDK
        run: |
          cd python-sdk
          pip install -r requirements.docs.txt
          pip install tox
          make docs
          mv docs/las.md ../reference/python-sdk/latest.md

      - name: Check out my java sdk
        uses: actions/checkout@master
        with:
          repository: LucidtechAI/las-sdk-java
          path: java-sdk

      - name: Java SDK
        run: |
          sudo apt-get install doxygen
          sudo apt-get install nodejs
          npm install moxygen
          cd java-sdk
          doxygen
          npx moxygen xml
          mv api.md ../reference/java/latest.md

      - name: Clean up
        run: |
          rm -rf java-sdk
          rm -rf python-sdk
          git stash push package-lock.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update SDK reference docs
          title: Update SDK reference docs
          body: This is an auto-generated PR with updated docs from the SDK.
          labels: automated pr
          branch: auto/update-sdk-reference
          base: master
