# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

---
name: Update SDK references

on:
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prerequisites
        run: |
          sudo apt-get install doxygen
          sudo apt-get install nodejs
          npm install moxygen

      - name: Check out python sdk
        uses: actions/checkout@master
        with:
          repository: LucidtechAI/las-sdk-python
          path: python-sdk

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Python SDK
        run: |
          cd python-sdk
          pip install -r requirements.docs.txt
          pip install tox
          make docs
          mv docs/las.md ../reference/python/latest.md

      - name: Check out java sdk
        uses: actions/checkout@master
        with:
          repository: LucidtechAI/las-sdk-java
          path: java-sdk

      - name: Java SDK
        run: |
          cd java-sdk
          doxygen
          npx moxygen xml
          mv api.md ../reference/java/latest.md

      - name: Check out .NET sdk
        uses: actions/checkout@master
        with:
          repository: LucidtechAI/las-sdk-net
          path: net-sdk

      - name: .NET SDK
        run: |
          cd net-sdk
          doxygen documentation.conf
          npx moxygen xml
          mv api.md ../reference/dotnet/latest.md

      - name: Check out java-script sdk
        uses: actions/checkout@master
        with:
          repository: LucidtechAI/las-sdk-js
          path: js-sdk

      - name: JavaScript SDK
        run: |
          cd js-sdk
          npm install && npm run upgrade-lucidtech
          npm run docs
          sed -i -E -e '/Defined in:.*/d' -e '/(Name|Type|Description) \|/d' -e '/------/d' -e 's/ \|//g' docs.md
          mv docs.md ../reference/js/latest.md

      - name: Clean up
        run: |
          rm -rf java-sdk
          rm -rf python-sdk
          rm -rf js-sdk
          rm -rf net-sdk
          rm package-lock.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update SDK reference docs
          title: Update SDK reference docs
          body: This is an auto-generated PR with updated docs from the SDK.
          labels: automated pr
          branch: auto/update-sdk-reference
          base: master
